Incr13
zlojkota/YL-1 pull request #13
Opened 2021-12-19 09:21 UTC by zlojkota

2021-12-21 14:28 UTC, Barugoo commented on cmd/agent/agent.go
> +	} else {
Здесь `else` лишний:
```go
res, err := p.client.Do(req)
if err != nil {
    log.Error(err)
    return
}
log.Print("StatusCode:", res.StatusCode, " URL:", req.URL.Path, ", Body:", string(buf))
```

2021-12-21 14:31 UTC, Barugoo commented on cmd/server/server.go
> +	var helper serverhandlers.Storager
`helper` слишком общее название для хранилки

2021-12-21 14:33 UTC, Barugoo commented on cmd/server/server.go
> +	if *cfg.DatabaseDsn == "" {
У тебя это условие повторяется в нескольких местах
Быть может лучше закинуть его в результат в именованную переменную и работать с ней?
```go
isDBAvailable := *cfg.DatabaseDsn == ""
if isDBAvailable {
//...
}
```

2021-12-21 14:37 UTC, Barugoo commented on internal/agentcollector/agentCollector.go
> +		strVal = strconv.FormatUint(*metrics.Delta, 10)
Рекомендую взять за привычку перед любым разыменовыванием указателя делать проверку на `nil`
```go
if metrics.Delta == nil {
    return nil, errors.New("invalid counter value")
}
strVal = strconv.FormatUint(*metrics.Delta, 10)
```

2021-12-21 14:39 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +		panic(err)
Давай лучше возвращать здесь ошибку, а не паниковать. Паника мы выкидываем только при **самых исключительных ситуациях**.

2021-12-21 14:39 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +	} else {
Здесь не нужен `else`)

2021-12-21 14:39 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +	Done         chan bool
Может быть лучше воспользоваться `context.Context`?

2021-12-21 14:40 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +		ss.db.QueryRow("SELECT count(id) FROM metrics WHERE id=$1 AND mtype=$2", val.ID, val.MType).Scan(&cnt)
Я бы все-таки рекомендовал обрабатывать все ошибки, а не опускать их

2021-12-21 14:42 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +		panic(err)
Мы не используем панику для обработки рядовых ошибок)

2021-12-21 14:42 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +			log.Error(err)
Здесь должен быть `return`

2021-12-21 14:43 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +		_ = rows.Err()
Зачем?)

2021-12-21 14:44 UTC, Barugoo commented on internal/filestorage/filestorage.go
> +		log.Error(err)
`return`?

2021-12-21 14:45 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +	counter := 100
Не очень говорящее название для переменной

2021-12-21 14:58 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +package dbstorage
Оставлять одиночные комментарии к запросам не вижу смысла (их будет много, проще голосом), обсудим на 1-1.

2021-12-21 15:00 UTC, Barugoo commented on internal/filestorage/filestorage.go
> +		case <-ss.Done:
Мы не можем гарантировать, что сработает этот кейс, а не вычитывание из канала `ss.Done` в `WaitDone`
Лучше используй `context.Context`.

2021-12-21 15:02 UTC, Barugoo commented on internal/serverhandlers/serverHandlers.go
> +type Storager interface {
Имена интерфейсов с припиской `-er` мы обычно образуем от глаголов. `Storage` - не глагол. 
Так что лучше сделать просто `type Storager` 
Тоже самое относится к `Stater`

2021-12-21 15:13 UTC, Barugoo requested changes
Не все 13 тестов зеленые
Есть вопросы по пакету dbStorage

2021-12-22 06:54 UTC, zlojkota commented on cmd/agent/agent.go
> +	} else {
Done

2021-12-22 06:57 UTC, zlojkota commented on cmd/server/server.go
> +	if *cfg.DatabaseDsn == "" {
Done

2021-12-22 06:58 UTC, zlojkota commented on cmd/server/server.go
> +	var helper serverhandlers.Storager
Done

2021-12-22 07:06 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +	counter := 100
Done

2021-12-22 07:08 UTC, zlojkota commented on internal/filestorage/filestorage.go
> +		log.Error(err)
Done

2021-12-22 07:10 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +			log.Error(err)
Done, replaced to 'continue'

2021-12-22 07:19 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +	} else {
Done

2021-12-22 07:33 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +		ss.db.QueryRow("SELECT count(id) FROM metrics WHERE id=$1 AND mtype=$2", val.ID, val.MType).Scan(&cnt)
Done

2021-12-22 07:33 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +		_ = rows.Err()
Done

2021-12-22 07:43 UTC, zlojkota commented on internal/agentcollector/agentCollector.go
> +		strVal = strconv.FormatUint(*metrics.Delta, 10)
Done

2021-12-22 17:15 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +		panic(err)
Up err to main.

2021-12-22 17:20 UTC, zlojkota commented on internal/serverhandlers/serverHandlers.go
> +type Storager interface {
Done

2022-01-05 06:23 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +	Done         chan bool
Done

2022-01-05 06:24 UTC, zlojkota commented on internal/filestorage/filestorage.go
> +		case <-ss.Done:
Done

2022-01-05 06:26 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +		panic(err)
Done

2022-01-11 12:28 UTC, Barugoo commented on internal/agentcollector/agentCollector.go
> +		p.serverAddr = fmt.Sprintf("http://%s", srvAddr)
Давай мы в адрес помимо непосредственно хоста и порта также утащим протокол, то есть:
```go
// a.cfg.Address == https://localhost:8080
url = fmt.Sprintf("%s/updates/", a.cfg.Address)
```
Зачем? Ну шобы можно было менять протокол (http/https) через конфиг, без необходимости лазить в код

2022-01-11 12:31 UTC, Barugoo commented on internal/dbstorage/dbstorage.go
> +
Очень круто, что ты подумал о гоночках!)

2022-01-11 12:32 UTC, Barugoo approved these changes
Отлично, так держать!

2022-01-11 18:01 UTC, zlojkota commented on internal/agentcollector/agentCollector.go
> +		p.serverAddr = fmt.Sprintf("http://%s", srvAddr)
done

2022-01-11 18:03 UTC, zlojkota commented on internal/dbstorage/dbstorage.go
> +
Пришлось. Я ж сразу параллельность задумал...

2022-01-11 18:04 UTC, merged