Code increment 1,2,3
zlojkota/YL-1 pull request #2
Opened 2021-12-01 12:55 UTC by zlojkota

2021-12-01 13:57 UTC, Barugoo commented on internal/collector/collector.go
> +func (asiwantsoicallIliketheletterpsmall *Collector) collect() {
Интересное название для обозначения экземпляра структуры внутри ее метода=)
Давай все же сократим до
```go
func (c *Collector) collect() {...}
```

2021-12-01 13:58 UTC, Barugoo commented on cmd/agent/agent.go
> +	duration time.Duration
Не очень информативное название переменной
Я понимаю, что требуется по заданию, но даже с этой информацией не понимаю длительность чего именно обозначает это поле. Это pollInterval или reportInterval? (и почему именно "длительность", а не период или интервал)

2021-12-01 14:01 UTC, zlojkota commented on internal/collector/collector.go
> +func (asiwantsoicallIliketheletterpsmall *Collector) collect() {
Да меня тут линтер не пускал, немножко бомбануло) сокращу до `func (col *Collector) collect() {...}`, так норм будет?

2021-12-01 14:02 UTC, Barugoo commented on cmd/agent/agent.go
> +		res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
Давай вынесем ту часть, которая обозначает в URL протокол, хост и порт в константу. А заодно и воспользуемся форматирующей функцией пакета `fmt` для формирования урла:
```go
const serverAddr = "http://localhost:8080"
///...
url := fmt.Sprintf("%s/update/gauge/%s/%s", serverAddr, string(key), strval)
res, err := http.Post(url, "text/plain", nil)
```

2021-12-01 14:12 UTC, Barugoo commented on cmd/agent/agent.go
> +			fmt.Println(err)
Круто, что ты логгируешь ошибку
Но нам незачем дальше выполнять эту функцию, если метод отправки запроса вернул ошибку. 
В данном же случае это еще и чревато паникой здесь:
```go
res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
if err != nil {
 	fmt.Println(err)
}
err = res.Body.Close() // <----
```
Обычно, в Go разработчики стараются придерживаться соглашения, что если функция возвращает `err != nil`, то все остальные возвращаемые значения (в данном случае `res`) лучше не трогать, тк они могут быть как `nil`, так и просто содержать неправильные данные. 
Так как `http.Post` - это функция стандартной библиотеки, она подчиняется этому принципу) Как и любой хороший код на Go, в общем-то

2021-12-01 14:13 UTC, Barugoo commented on cmd/agent/agent.go
> +			fmt.Println(err)
tl;dr если у тебя происходит ошибка в этой функции - ты ее логгируешь и делаешь `return`:
```go
res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
if err != nil {
 	fmt.Println(err)
        return
}

2021-12-01 14:17 UTC, Barugoo commented on cmd/agent/agent.go
> +			fmt.Println(err)
А еще для логгирования лучше использовать пакет `log`
Почему? Во-первых он, в отличии от `fmt` позволяет установить в качестве потока вывода не только stdout, но и любой другой объект, который удовлетворяет интерфейсу `io.Writer`. Это может быть открытый файл, открытое подключение и тд.
То есть ты легко можешь перенаправить вывод всех логов в программе в файлик просто подменив поток вывода для пакета `log`. По умолчанию, так же как и для `fmt` это stdout

А во-вторых - лог добавляет к каждому сообщению также дату и время, в которое оно было напечатано, что удобно.

2021-12-01 14:22 UTC, Barugoo commented on cmd/agent/agent.go
> +		err = res.Body.Close()
Лучшая практика - вызывать закрывающие методы через `defer`. При этом делать это только в том случае, если мы уверены, что тело валидно (в случае http-клиента). Обычно для этого достаточно удостовериться, что функция, которой ты делаешь запрос на сервер, не вернула ошибку.

Выглядеть на мой взгляд это должно примерно вот так:
```go
res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
if err != nil {
 	fmt.Println(err)
        return // <--- не забываем про ретурн
}
defer res.Body.Close()
```
Кстати говоря, ошибку, которую возвращают `Close()` методы у `io.WriteCloser` и `io.ReadCloser` обычно не обрабатывают и не логгируют - смысл? Она ничего тебе не даст (тк обычно происходит когда коннект УЖЕ разорван, или файл УЖЕ закрыт), только усложнит код.

2021-12-01 14:24 UTC, Barugoo commented on cmd/agent/agent.go
> +		res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
А зачем ты приводишь `key` к строке? Это же итак строка.

2021-12-01 14:24 UTC, Barugoo commented on cmd/agent/agent.go
> +		strval := fmt.Sprintf("%d", val)
Для интов лучше использовать `strconv.Itoa`

2021-12-01 14:27 UTC, Barugoo commented on internal/collector/collector.go
> +	Done     <-chan struct{}
Так и не нашел кто в коде пишет в этот канал.
Если он не используется лучше его выпилить.

2021-12-01 14:27 UTC, Barugoo commented on internal/collector/collector.go
> +	duration time.Duration
Длительность чего опять же?

2021-12-01 14:29 UTC, Barugoo commented on internal/serverheaders/serverHeaders.go
> +package serverheaders
Несовсем понял, как связан этот пакет и заголовки сервера? 
Или это очепятка и должно быть `package serverhandlers`?

2021-12-01 14:30 UTC, Barugoo commented on internal/serverheaders/serverHeaders.go
> +	"strconv"
Лучше (для читаемости) разносить импорты стандартной библиотеки, сторонних библиотек и собственных пакетов на разные блоки:
```go
import (
	"fmt"
  	"net/http"
  	"strconv"

  	"github.com/labstack/echo/v4"
)
```

2021-12-01 14:31 UTC, Barugoo commented on internal/serverheaders/serverHeaders.go
> +	tableHead := "<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" style=\"width:100%\">\n<thead>\n<tr>\n<th scope=\"col\">ID</th>\n<th scope=\"col\">Metric name</th>\n<th scope=
Давай вытащим html-шаблоны в константы, а лучше в отдельный файл
Потому что в текущем виде поддерживать другому разработчику этот код будет очень непросто

2021-12-01 14:32 UTC, Barugoo commented on internal/serverheaders/serverHeaders.go
> +	case "counter":
Давай вынесем типы метрик в константы

2021-12-01 14:34 UTC, Barugoo commented on cmd/agent/agent.go
> +func (p *Agent) HandleData(counter map[string]int64, gauge map[string]float64) {
Неинформативное название метода
Давай лучше сделаем `SendMetrics` или `ReportMetrics`

2021-12-01 14:35 UTC, Barugoo commented on internal/serverheaders/serverHeaders.go
> +	tableHead := "<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" style=\"width:100%\">\n<thead>\n<tr>\n<th scope=\"col\">ID</th>\n<th scope=\"col\">Metric name</th>\n<th scope=
Почитай про библиотеку html/template и как с ней работать в Гошке
В Go неплохой язык шаблонов (хоть в питоне он гораздо круче) и отлично подходит для этого кейса

2021-12-01 14:37 UTC, Barugoo commented on cmd/server/server.go
> +	e.POST("/:method/:type/:metric/:value", handler.UpdateHandler)
Зачем нам делать `method` параметром урла, если функция-обработчик выполняет всегда только `Update`?
Если сделать так:
```go
e.POST("/update/:type/:metric/:value", handler.UpdateHandler)
```
то ты избавишься от необходимости проверять в самой функции-обработчики метод на соответствие.

2021-12-01 14:38 UTC, Barugoo requested changes
Неплохо
Жду доработанной версии=)

2021-12-02 09:50 UTC, zlojkota commented on cmd/agent/agent.go
> +	duration time.Duration
Done

2021-12-02 09:51 UTC, zlojkota commented on cmd/agent/agent.go
> +func (p *Agent) HandleData(counter map[string]int64, gauge map[string]float64) {
Done

2021-12-02 09:53 UTC, zlojkota commented on cmd/agent/agent.go
> +		res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
Done

2021-12-02 09:57 UTC, zlojkota commented on cmd/agent/agent.go
> +		res, err := http.Post("http://localhost:8080/update/gauge/"+string(key)+"/"+strval, "text/plain", nil)
Done

2021-12-02 09:58 UTC, zlojkota commented on cmd/agent/agent.go
> +			fmt.Println(err)
Done

2021-12-02 09:58 UTC, zlojkota commented on cmd/agent/agent.go
> +		err = res.Body.Close()
Done

2021-12-02 10:03 UTC, zlojkota commented on cmd/agent/agent.go
> +		strval := fmt.Sprintf("%d", val)
Not Done - Itoa - int32. My type - int64

2021-12-04 15:30 UTC, zlojkota commented on cmd/server/server.go
> +	e.POST("/:method/:type/:metric/:value", handler.UpdateHandler)
Done

2021-12-04 15:30 UTC, zlojkota commented on internal/collector/collector.go
> +	duration time.Duration
Done

2021-12-04 15:32 UTC, zlojkota commented on internal/collector/collector.go
> +	Done     <-chan struct{}
Done

2021-12-04 15:32 UTC, zlojkota commented on internal/collector/collector.go
> +func (asiwantsoicallIliketheletterpsmall *Collector) collect() {
Done

2021-12-04 15:32 UTC, zlojkota commented on internal/serverheaders/serverHeaders.go
> +package serverheaders
Done

2021-12-04 15:33 UTC, zlojkota commented on internal/serverheaders/serverHeaders.go
> +	"strconv"
Done

2021-12-05 09:10 UTC, zlojkota commented on internal/serverheaders/serverHeaders.go
> +	tableHead := "<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" style=\"width:100%\">\n<thead>\n<tr>\n<th scope=\"col\">ID</th>\n<th scope=\"col\">Metric name</th>\n<th scope=
Done

2021-12-05 09:14 UTC, zlojkota commented on internal/serverheaders/serverHeaders.go
> +	case "counter":
Done

2021-12-07 10:45 UTC, Barugoo commented on cmd/agent/agent.go
> +			if err != nil {
> Кстати говоря, ошибку, которую возвращают Close() методы у io.WriteCloser и io.ReadCloser обычно не обрабатывают и не логгируют - смысл? Она ничего тебе не даст (тк обычно происходит когда коннект УЖЕ разорван, или файл УЖЕ закрыт), только усложнит код.

2021-12-07 10:53 UTC, Barugoo approved these changes
Работу принимаю

2021-12-07 11:03 UTC, merged